site_name: Estrade
site_description: Build, Backtest and Go Live your own trading bots
site_author: Gabriel Oger
site_url: "https://estrade.readthedocs.io/"

repo_name: cimourdain/estrade
repo_url: https://github.com/cimourdain/estrade
edit_uri: ""

dev_addr: "0.0.0.0:8000"

theme:
  name: 'material'

markdown_extensions:
  - codehilite
  - admonition
  - codehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tasklist

plugins:
  - mkdocstrings:
      default_handler: python
      handlers:
          python:
              selection:
                inherited_members: true
              rendering:
                  heading_level: 3
      watch:
        - estrade
        - tests

nav:
  - Home: index.md
  - Install: install.md
  - Tutorial: tutorial.md
  - Guide:
      Tick: guide/tick.md
      Epic: guide/epic.md
  - Reference:
      Tick: reference/tick.md
      Epic: reference/epic.md
      Tick Provider: reference/tick_provider.md
      Trade: reference/trade.md
      Trade Provider: reference/trade_provider.md
      Strategy: reference/strategy.md
      FrameSet: reference/graph/frame_set.md
      BaseIndicators: reference/graph/base_indicators.md
      Indicators:
          - Candle Sets: reference/graph/indicators/candle_set.md
          - Simple Moving Average: reference/graph/indicators/simple_moving_average.md
          - Pivot: reference/graph/indicators/pivot.md
          - RSI: reference/graph/indicators/rsi.md
      Enums: reference/enums.md
      Reporting:
          - CSV: reference/reporting/csv.md
  - Changelog: changelog.md
  - Roadmap: ROADMAP.md
  - Contributing: contributing.md
